apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-nginx-deployment
spec:
  selector:
    matchLabels:
      app: k8-nginx
  template:
    metadata:
      labels:
        app: k8-nginx
    spec:
      containers:
      - name: k8-nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
