# kubectl create secret generic db-secret --from-literal=DB_Host=sql01 --from-literal=DB_User=root --from-literal=DB_Password=password123
# kubectl get secret db-secret -o yaml
# kubectl apply -f pod-secret.yaml
# kubectl exec -it my-nginx -- bash
# echo $SECRET_PASSWORD
apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    name: my-nginx
spec:
  containers:
  - name: my-nginx
    image: nginx:1.16
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: db-secret
            key: DB_User
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-secret
            key: DB_Password
      - name: SECRET_HOST
        valueFrom:
          secretKeyRef:
            name: db-secret
            key: DB_Host
