apiVersion: v1
kind: Pod
metadata:
  name: k8-nginx
  labels:
    name: k8-nginx
spec:
  containers:
  - name: nginx-ctr
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
