apiVersion: v1
kind: Pod
metadata:
  name: k8-nginx
  labels:
    app: k8-nginx
    color: red
    type: webserver
  annotations:
    imageregistry: https://hub.docker.com/poPath
    version: v1
spec:
  volumes:
    - name: nginx-data
      hostPath:
        path: "/Users/emadnajeeb/Documents/development/k8s-practice/tmp"
  containers:
  - name: nginx-ctr
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: "/tmp"
        name: nginx-data
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: db-secret
            key: DB_User
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-secret
            key: DB_Password
      - name: SECRET_HOST
        valueFrom:
          secretKeyRef:
            name: db-secret
            key: DB_Host