apiVersion: v1
kind: ReplicationController
metadata:
  name: k8-nginx-rc
spec:
  replicas: 5
  selector:
    app: k8-nginx
  template:
    metadata:
      name: k8-nginx
      labels:
        app: k8-nginx
    spec:
      containers:
        - name: k8-nginx-ctr
          image: nginx
          ports:
            - containerPort: 80