apiVersion: v1
kind: Service
metadata:
  name: k8-nginx-svc
  labels:
    app: k8-nginx-svc
spec:
  type: NodePort
  selector:
    app: k8-nginx
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
